version: '3'

services:
  websocket_server:
    environment:
      - NOTIFICATIONS_HOST=${NOTIFICATIONS_HOST}
      - NOTIFICATIONS_PORT=${NOTIFICATIONS_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_TCP_PORT=${RABBITMQ_TCP_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    image: python-ws-server
    ports:
      - '${NOTIFICATIONS_PORT}:${NOTIFICATIONS_PORT}'
    external_links:
      - 'localhost:127.0.0.1'
